/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ../../../public/mapceu/teste4/ceu.gltf -t 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Laje_Parapeito: THREE.Mesh
  }
  materials: {
    Material__14255: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/mapceu/teste4/ceu.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-25.761, 3.73, 51.284]} rotation={[-Math.PI / 2, 0, 0.348]}>
        <mesh geometry={nodes.Laje_Parapeito.geometry} material={materials.Material__14255} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/ceu.gltf')
