import {
  carrent,
  creator,
  css,
  docker,
  figma,
  git,
  html,
  javascript,
  jobit,
  meta,
  mobile,
  mongodb,
  nodejs,
  reactjs,
  redux,
  shopify,
  starbucks,
  observacao,
  planetarium,
  tailwind,
  tesla,
  threejs,
  tripguide,
  typescript,
  web,
} from "@/../public/assets";

export const navLinks = [
  {
    id: "estrutura",
    title: "Estrutura",
    link: "/estrutura",
  },
  {
    id: "atividades",
    title: "Atividades",
    link: "/atividades",
  },
  {
    id: "escolas",
    title: "Escolas & Colégios",
    link: "/escolas",
  },
  {
    id: "publico",
    title: "Atendimento ao Público",
    link: "/publico",
  },
  {
    id: "corporativo",
    title: "Eventos Corporativos",
    link: "/corporativo",
  },
  // {
  //   id: "blog",
  //   title: "Blog",
  //   link: "/blog",
  // },
];

const structure = [
  {
    id: 0,
    name: "Auditório",
    description: `Com capacidade para 130 pessoas, o auditório é onde ocorrem as apresentações multimídias e palestras em locações empresarias. Sua estrutura adaptável também permite oferecer maior comodidade para as atividades, de acordo com a demanda de cada instituição.`,
    staticImage: "/images/structure/auditorio.jpg",
    tourId: 5,
  },
  {
    id: 1,
    name: "Planetário",
    description: `Sala com capacidade de 65 pessoas, com teto em formato de domo, onde são projetadas imagens através de um projetor em formato 360ºx180º. Seu formato digital permite a exibição de filmes imersivos de várias aréas do conhecimento humano.`,
    staticImage: "/images/structure/planetario.jpg",
    tourId: 13,
  },
  {
    id: 2,
    name: "Aquário",
    description: `Salão onde ocorrem algumas das oficinas interativas para escolas. Aqui ocorrem também reuniões corporativas, com todo o aparato multimídia disponível.`,
    staticImage: "/images/structure/aquario.jpg",
    tourId: 4,
  },
  {
    id: 3,
    name: "Geo-show",
    description: `Paredão colorido de 20 metros de comprimento que representa o perfil geológico do Estado de São Paulo. Neste local contamos a história do nosso planeta e dos períodos geológicos da Terra.`,
    staticImage: "/images/structure/geo-show.jpeg",
    tourId: 11,
  },
  {
    id: 4,
    name: "Caverna",
    description: `Espaço subterrâneo com cerca de 200 m² representando um caverna cenográfica. Neste local acontecem as oficinas de geologia de indentificação de rochas e fósseis e também festas de formatura promovidas pela Peraltas ALL PARTY.`,
    staticImage: "/images/structure/caverna.jpg",
    tourId: 7,
  },
  {
    id: 5,
    name: "Base de Lançamentos",
    description: `Nesta base com casa-mata e torre de lançamento, realizamos a oficina "PHOBOS - O Foguete" que lança minifoguetes que podem atingir 200 metros no seu apogeu. Comporta foguetes de até 2 metros de altura, por esse motivo é utilizada por diversas intituições para lançamentos.`,
    staticImage: "/images/structure/base-de-lancamento.jpg",
    tourId: 6,
  },
  {
    id: 6,
    name: "Observatório",
    description: `Cúpula de observação equipada com um dos mais modernos telescópios eletrônicos disponíveis ao público no Brasil. Neste telescópio é possivel a observação de planetas, estrelas, aglomerados, nebulosas e galáxias.`,
    staticImage: "/images/structure/observatorio.jpg",
    tourId: 8,
  },
  {
    id: 7,
    name: "Stonehenge",
    description: `Considerado um dos mais antigos observatórios astronômicos, o monumento que fica em Salisbury, Inglaterra, foi construido há 5 mil anos e era multifuncional. A nossa réplica é cerca de 3x menor que a original e auxilia na explicação sobre a evolução dos meios de observação do céu com o passar do tempo.`,
    staticImage: "/images/structure/stonehenge.jpeg",
    tourId: 15,
  },
  {
    id: 8,
    name: "Relógio de Sol",
    description: `Relógio de sol analemático construido no jardim, onde o ponteiro é a própria pessoa. Ele é utilizado para os estudantes compararem com o relógio de sol construido na oficina "O Céu na régua e compasso"`,
    staticImage: "/images/structure/relogio-de-sol.jpeg",
    tourId: 14,
  },
  {
    id: 9,
    name: "Estação Meteorológica",
    description: `Estação automática para coleta de dados meteorológicos, que podem ser usadas em oficinas interativas. São coletados dados de temperatura, precipitação, humidade do ar, velocidade do vento e radiação solar.`,
    staticImage: "/images/structure/estacao-meteorologica.jpeg",
    tourId: 14,
  },
  {
    id: 10,
    name: "Alossauro",
    description: `Replica em tamanho real do fóssil de um Alossauro.`,
    staticImage: "/images/structure/alossauro.jpeg",
    tourId: 3,
  },
];

const activities = [
  {
    id: "1",
    title: "atividade 1",
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda blanditiis dignissimos hic iusto
                nesciunt odio, odit repellendus sapiente veniam voluptate. Ad commodi hic ipsum itaque molestiae quo
                recusandae velit voluptas.
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda blanditiis dignissimos hic iusto
                nesciunt odio, odit repellendus sapiente veniam voluptate. Ad commodi hic ipsum itaque molestiae quo
                recusandae velit voluptas.`,
    video: "/video.mp4",
  },
  {
    id: "2",
    title: "atividade 2",
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda blanditiis dignissimos hic iusto
                nesciunt odio, odit repellendus sapiente veniam voluptate. Ad commodi hic ipsum itaque molestiae quo
                recusandae velit voluptas.
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda blanditiis dignissimos hic iusto
                nesciunt odio, odit repellendus sapiente veniam voluptate. Ad commodi hic ipsum itaque molestiae quo
                recusandae velit voluptas.`,
    video: "/video2.mp4",
  },
];

const activitiesList = [
  {
    id: 1,
    type: "workshop",
    title: "Energias",
    images: [
      "https://images.pexels.com/photos/4338617/pexels-photo-4338617.jpeg?auto=compress&cs=tinysrgb&w=600",
    ],
    description: `Em grupo, os estudantes analisam características de cidades fictícias e trabalham em um plano de gestão para ampliação e geração de energia. Neste processo, é possível compreender as variações de sua produção em usinas hidrelétricas, termoelétricas, termonucleares, eólicas e solares. Os grupos também discutem entre si sobre as soluções apresentadas mostrando vantagens e desvantagens do uso de cada matriz energética escolhida.`,
    subjects: [
      { title: "Ciências", color: "text-blue-300" },
      { title: "Geografia", color: "text-orange-300" },
      { title: "Meio Ambiente", color: "text-green-300" },
      { title: "Física", color: "text-green-500" },
    ],
    topics: [
      "Definição de tipos de energia",
      "Matrizes energéticas disponíveis ( Hidroelétrica, Solar, Nuclear, Termonuclear, Eólica )",
      "Sustentabilidade",
      "Dinâmica de trabalho em equipe",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "6°ano", color: "text-emerald-600" },
      { title: "7°ano", color: "text-emerald-700" },
      { title: "8°ano", color: "text-emerald-800" },
      { title: "9°ano", color: "text-emerald-900" },
      { title: "1°ano[E.M.]", color: "text-lime-100" },
      { title: "2°ano[E.M.]", color: "text-lime-200" },
      { title: "3°ano[E.M.]", color: "text-lime-300" },
    ],
  },
  {
    id: 2,
    title: "A Família do Sol",
    type: "multimedia",
    images: [
      "/images/Multimedias/A Familia do Sol/Banner Solar System.jpg",
      "/images/Multimedias/A Familia do Sol/Ani Frame 04.bmp",
      "/images/Multimedias/A Familia do Sol/Ani Frame 02.bmp",
      "/images/Multimedias/A Familia do Sol/Ani Frame 03.bmp",
      "/images/Multimedias/A Familia do Sol/Ani Frame 05.bmp",
      "/images/Multimedias/A Familia do Sol/Familia do Sol Titulo.bmp",
      "/images/Multimedias/A Familia do Sol/Jupiter Luas Galileanas.bmp",
      "/images/Multimedias/A Familia do Sol/Jupiter Luas Pastoras.bmp",
      "/images/Multimedias/A Familia do Sol/Mercurio Temperatura.bmp",
      "/images/Multimedias/A Familia do Sol/Panel Planets Last Frame 3.bmp",
      "/images/Multimedias/A Familia do Sol/Ship Saturno 2.jpg",
      "/images/Multimedias/A Familia do Sol/Ship Saturno.jpg",
      "/images/Multimedias/A Familia do Sol/Solar System.jpg",
      // "/images/Multimedias/A Familia do Sol/Thumb Areas Base.psd",
    ],
    description: `Simulação de uma viagem pelo Sistema Solar, onde visitamos o Sol, os oito planetas, luas mais importantes, cometas e asteróides. Para cada objeto descrevemos suas características físicas (tamanho, temperatura, composição) e orbitais (distância e período de revolução). Comparamos estas características com a Terra que é também detalhada ao final da viagem. Durante o passeio passamos pelas superfícies de alguns planetas e mostramos que a Terra é o único planeta com condições para abrigar seres vivos como nós.`,
    subjects: [
      { title: "Ciências", color: "text-blue-300" },
      { title: "Astronomia", color: "text-blue-300" },
      { title: "Geografia", color: "text-orange-300" },
    ],
    topics: [
      "Tipos de objetos do Sistema Solar ( sol, planetas, luas, asteróides e cometas )",
      "Características físicas dos planetas ( diâmetro, temperatura, composição )",
      "Características orbitais dos planeas ( revolução, rotação )",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "3°ano", color: "text-emerald-300" },
      { title: "4°ano", color: "text-emerald-400" },
      { title: "5°ano", color: "text-emerald-500" },
    ],
  },
  {
    id: 3,
    title: "Gravidade Zero",
    type: "multimedia",
    images: [
      "/images/Multimedias/Gravidade Zero/image-5.jpeg",
      "/images/Multimedias/Gravidade Zero/image-3.jpeg",
      "/images/Multimedias/Gravidade Zero/image-1.jpeg",
      "/images/Multimedias/Gravidade Zero/image-2.jpeg",
      "/images/Multimedias/Gravidade Zero/image-4.jpeg",
    ],
    description: `Iniciamos com uma rápida introdução a história da aviação e da astronáutica mostrando algumas pessoas que foram importantes neste campo da ciência, como Santos Dumont e Verner Von Braun. A seguir apresentamos os componentes e funções de alguns foguetes e sua evolução. Comenta-se sobre a exploração do espaço, desde a corrida espacial com destino a Lua até os dias de hoje com o turismo espacial. Finalmente exploramos como o corpo humano reage ao ambiente espacial e o que é preciso para ser um astronauta.`,
    subjects: [
      { title: "Astronáutica", color: "text-blue-500" },
      { title: "Astronomia", color: "text-blue-300" },
      { title: "Geografia", color: "text-orange-300" },
      { title: "História", color: "text-brown-300" },
      { title: "Física", color: "text-green-500" },
    ],
    topics: [
      "Funcionamento e importância dos foguetes",
      "Missões Apollo",
      "Veículos espaciais",
      "Estação Espacial Internacional",
      "Corpo Humano em baixa gravidade",
      "Tecnologia aeroespacial",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "5°ano", color: "text-emerald-500" },
      { title: "6°ano", color: "text-emerald-600" },
      { title: "7°ano", color: "text-emerald-700" },
      { title: "8°ano", color: "text-emerald-800" },
      { title: "9°ano", color: "text-emerald-900" },
      { title: "1°ano[E.M.]", color: "text-lime-100" },
      { title: "2°ano[E.M.]", color: "text-lime-200" },
      { title: "3°ano[E.M.]", color: "text-lime-300" },
    ],
  },
  {
    id: 4,
    title: "Geometria Cósmica",
    type: "multimedia",
    images: [
      "/images/Multimedias/Gometria Cosmica/Relogio de Sol.jpg",
      "/images/Multimedias/Gometria Cosmica/Sistema Geocentrico.jpg",
      "/images/Multimedias/Gometria Cosmica/image1.jpeg",
      "/images/Multimedias/Gometria Cosmica/image2.jpeg",
      "/images/Multimedias/Gometria Cosmica/image3.jpeg",
    ],
    description: `Descrição da história da Astronomia com personagens importantes como Ptolomeu, Galileu e Copérnico e suas contribuições para nossa visão de Universo. A seguir explicam-se os fenômenos do Sistema Sol-Terra-Lua, incluindo calendários, estações do ano, fases da Lua e eclipses.`,
    subjects: [
      { title: "Astronomia", color: "text-blue-300" },
      { title: "Ciências", color: "text-blue-300" },
      { title: "Geografia", color: "text-orange-300" },
      { title: "História", color: "text-brown-300" },
      { title: "Matemática", color: "text-yellow-200" },
    ],
    topics: [
      "História da Astronomia",
      "Sistemas de mundos",
      "Estações do ano",
      "Fases da Lua",
      "Eclipses",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "6°ano", color: "text-emerald-600" },
      { title: "7°ano", color: "text-emerald-700" },
      { title: "8°ano", color: "text-emerald-800" },
      { title: "9°ano", color: "text-emerald-900" },
      { title: "1°ano[E.M.]", color: "text-lime-100" },
      { title: "2°ano[E.M.]", color: "text-lime-200" },
      { title: "3°ano[E.M.]", color: "text-lime-300" },
    ],
  },
  {
    id: 5,
    title: "Albedo 0.39",
    type: "multimedia",
    images: [
      "/images/Multimedias/Albedo 0.39/Capturar 05.PNG",
      "/images/Multimedias/Albedo 0.39/Mount Sant Helens 01.jpg",
      "/images/Multimedias/Albedo 0.39/Capturar 01.PNG",
      "/images/Multimedias/Albedo 0.39/Capturar 02.PNG",
      "/images/Multimedias/Albedo 0.39/Capturar 03.PNG",
      "/images/Multimedias/Albedo 0.39/Capturar 04.PNG",
      "/images/Multimedias/Albedo 0.39/Capturar 06.PNG",
      "/images/Multimedias/Albedo 0.39/Capturar 07.PNG",
    ],
    description: `Uma viagem de estudo do planeta Terra, onde são descritas as características da sua superfície, estrutura intera e fenômenos que ocorrem na crosta terrestre. São explicados a formação de vulções, cordilheiras de montanhas, deriva continental, terremotos, maremotos e suas conseqüências para nós.`,
    subjects: [
      { title: "Ciências", color: "text-blue-300" },
      { title: "Geografia", color: "text-orange-300" },
      { title: "Geologia", color: "text-orange-600" },
    ],
    topics: [
      "Estrutura interna da Terra",
      "Vulcões",
      "Terremotos",
      "Maremotos",
      "Placas Tectônicas",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "6°ano", color: "text-emerald-600" },
      { title: "7°ano", color: "text-emerald-700" },
      { title: "8°ano", color: "text-emerald-800" },
      { title: "9°ano", color: "text-emerald-900" },
      { title: "1°ano[E.M.]", color: "text-lime-100" },
    ],
  },
  {
    id: 6,
    title: "Jornada nas Estrelas",
    type: "multimedia",
    images: [
      "/images/Multimedias/Jornada nas Estrelas/Cartog_Yellow_Star.jpg",
      "/images/Multimedias/Jornada nas Estrelas/Sky Tour First Frame.jpg",
      "/images/Multimedias/Jornada nas Estrelas/Stars Colours_Last_Frame.jpg",
      "/images/Multimedias/Jornada nas Estrelas/image1.jpeg",
    ],
    description: `Viagem interestelar simulada, onde mostramos as características físicas das estrelas, como temperaturas, tamanhos, distâncias e classificações básicas. A seguir explica-se o ciclo de formação de estrelas no interior de nebulosas, os tipos de nebulosas e a destruição de estrelas que podem gerar objetos como pulsares e buracos negros.Também é explicado o conceito de galáxia e demonstrado o tamanho do Universo observável.`,
    subjects: [
      { title: "Ciências", color: "text-blue-300" },
      { title: "Geografia", color: "text-orange-300" },
      { title: "Astronomia", color: "text-blue-300" },
      { title: "Matemática", color: "text-yellow-200" },
      { title: "Física", color: "text-green-500" },
      { title: "Química", color: "text-blue-900" },
    ],
    topics: [
      "Unidade de medidas estelar ( ano-luz )",
      "Características físicas de estrelas",
      "Tipos de objetos ( estrelas, nebulosas, pulsares, buracos negros )",
      "Evolução estelar",
      "Conceitos de galáxia e Universo",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "7°ano", color: "text-emerald-700" },
      { title: "8°ano", color: "text-emerald-800" },
      { title: "9°ano", color: "text-emerald-900" },
      { title: "1°ano[E.M.]", color: "text-lime-100" },
      { title: "2°ano[E.M.]", color: "text-lime-200" },
      { title: "3°ano[E.M.]", color: "text-lime-300" },
    ],
  },
  {
    id: 7,
    title: "Turma Alto Astral",
    type: "planetarium",
    images: [
      "/images/Planetarios/Alto Astral/Alto-Astral-01.png",
      "/images/Planetarios/Alto Astral/Alto-Astral-02.png",
      "/images/Planetarios/Alto Astral/Alto-Astral-03.png",
      "/images/Planetarios/Alto Astral/Alto-Astral-04.png",
      "/images/Planetarios/Alto Astral/Alto-Astral-05.png",
      "/images/Planetarios/Alto Astral/Alto-Astral-06.png",
    ],
    description: `Os alunos interagem com a turma alto astral em busca de pistas misteriosas para salvar o planeta Terra, incentivando a conscientização, respeito ao próximo, trabalho em grupo e a preservação do planeta.`,
    subjects: [
      { title: "Astronomia", color: "text-blue-300" },
      { title: "Meio Ambiente", color: "text-green-300" },
    ],
    topics: [
      "Recursos naturais",
      "Sustentabilidade",
      "Planetas do Sistema Solar",
    ],
    tags: [
      { title: "1°ano", color: "text-emerald-100" },
      { title: "2°ano", color: "text-emerald-200" },
      { title: "3°ano", color: "text-emerald-300" },
    ],
  },
  {
    id: 8,
    title: "Endereço Espacial",
    type: "planetarium",
    images: [
      "/images/Planetarios/Endereço Espacial/Frame Endereco Espacial 01.jpg",
    ],
    description: `Com os robozinhos Teka e Tiko, os alunos participam de uma aventura para salvar um bebê alienígena que se perdeu e veio parar na Terra. Nesta jornada, os estudantes acompanham o desafio de localizar a casa do bebê alienígena no universo e, geograficamente, aprendem a identificar regiões, bairros, estados, países, continentes, planetas, galáxias e grupos de galáxias para terem assim uma ideia geral do tamanho de nosso Universo.`,
    subjects: [
      { title: "Astronomia", color: "text-blue-300" },
      { title: "Geografia", color: "text-orange-300" },
      { title: "Valores Humanos", color: "text-blue-100" },
      { title: "Responsabilidade", color: "text-violet-500" },
      { title: "Coragem", color: "text-green-500" },
    ],
    topics: [
      "Localização geográfica ( bairro, cidade, região, estado, pais, continente, planeta )",
      "Localização espacial ( demais planetas, estrelas, galáxias, aglomerados de galáxias )",
    ],
    tags: [
      { title: "2°ano", color: "text-emerald-200" },
      { title: "3°ano", color: "text-emerald-300" },
      { title: "4°ano", color: "text-emerald-400" },
    ],
  },
  {
    id: 9,
    title: "Filhos do Sol",
    type: "planetarium",
    images: [
      "/images/Planetarios/Filhos do Sol/Filhos do Sol.jpg",
      "/images/Planetarios/Filhos do Sol/Marte Frame.jpg",
      "/images/Planetarios/Filhos do Sol/Saturno Frame.jpg",
    ],
    description: `Através de um tour  pelo Sistema Solar, a sessão apresenta as principais características dos seus componentes, partindo da Terra em direção ao Sol e seguindo até os planetas, asteroides, planetas anões e cometas. Em cada componente são apresentadas as informações e caracteristicas mais relevantes associando ao conteúdo da grade de ciências abordados, principalmente, no Ensino Fundamental.`,
    subjects: [
      { title: "Astronomia", color: "text-blue-300" },
      { title: "Geografia", color: "text-orange-300" },
      { title: "Ciências", color: "text-blue-300" },
    ],
    topics: [
      "Sol",
      "Planetas do Sistema Solar",
      "Planetas Anões",
      "Cometas",
      "Vida na Terra",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "3°ano", color: "text-emerald-300" },
      { title: "4°ano", color: "text-emerald-400" },
      { title: "5°ano", color: "text-emerald-500" },
    ],
  },
  {
    id: 10,
    title: "Micromonstros",
    type: "planetarium",
    images: [
      "/images/Planetarios/Micromonstros/Piolhos 3200x3200.jpg",
      "/images/Planetarios/Micromonstros/Pulga 3200x3200.jpg",
      "/images/Planetarios/Micromonstros/Kid+Dog Capa.jpg",
    ],
    description: `Em uma viagem microscópica, os estudantes podem conhecer alguns seres invisíveis aos nossos olhos e que podem nos fazer mal: piolhos, vermes, pulgas, carrapatos e bactérias em estilo de desenho animado. Tudo isso, explorando o mundo invisível no quarto de uma criança.`,
    subjects: [
      { title: "Biologia", color: "text-green-200" },
      { title: "Higiene", color: "text-white-300" },
      { title: "Doenças", color: "text-yellow-800" },
      { title: "Parasitismo", color: "text-red-800" },
      { title: "Simbiose", color: "text-black-400" },
    ],
    topics: [
      "Piolhos",
      "Pulgas",
      "Percevejos",
      "Ácaros",
      "Tênia",
      "Protozoários",
      "Plasmodium",
      "Bactérias",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "4°ano", color: "text-emerald-400" },
      { title: "5°ano", color: "text-emerald-500" },
      { title: "6°ano", color: "text-emerald-600" },
    ],
  },
  {
    id: 11,
    title: "Palco Celeste",
    type: "planetarium",
    images: [
      "/images/Planetarios/Palco Celeste/Palco Celeste Contelations.jpg",
      "/images/Planetarios/Palco Celeste/Palco Celeste Frame 01.jpg",
      "/images/Planetarios/Palco Celeste/Palco Celeste Frame 02.jpg",
    ],
    description: `Essa sessão aborda a nossa visão do céu noturno, longe da poluição luminosa produzida pelas cidades e mostra o que podemos ver sem o uso de telescópios. É feito o reconhecimento de constelações de verão e inverno para o hemisfério Sul e a seguir viajamos no tempo para diferentes locais da Terra, para que o espectador presencie o acontecimento de eventos astronômicas como auroras, cometas e chuvas de meteoros.`,
    subjects: [
      { title: "Astronomia", color: "text-blue-300" },
      { title: "Ciências", color: "text-blue-300" },
      { title: "Geografia", color: "text-orange-300" },
      { title: "História", color: "text-brown-300" },
      { title: "Física", color: "text-green-500" },
    ],
    topics: [
      "Visão do céu a olho nú",
      "Poluição luminosa",
      "Constelações",
      "Fenômenos celestes",
      "Chuva de meteoros",
      "Cometas",
      "Lua",
      "Eclipses",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "5°ano", color: "text-emerald-500" },
      { title: "6°ano", color: "text-emerald-600" },
      { title: "7°ano", color: "text-emerald-700" },
      { title: "8°ano", color: "text-emerald-800" },
      { title: "9°ano", color: "text-emerald-900" },
      { title: "1°ano[E.M.]", color: "text-lime-100" },
      { title: "2°ano[E.M.]", color: "text-lime-200" },
      { title: "3°ano[E.M.]", color: "text-lime-300" },
    ],
  },
  {
    id: 12,
    title: "Irmãos de Gaia",
    type: "planetarium",
    images: [
      "https://images.pexels.com/photos/4737484/pexels-photo-4737484.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    ],
    description: `Essa sessão aborda o surgimento do Sistema Solar, a formação dos planetas rochosos e gasosos e sua estrutura interior. Presenciamos a evolução do sistema solar até à morte de nossa estrela. A sessão apresenta ainda conceitos de geologia e planetologia.`,
    subjects: [
      { title: "Astronomia", color: "text-blue-300" },
      { title: "Ciências", color: "text-blue-300" },
      { title: "Química", color: "text-blue-900" },
      { title: "Geografia", color: "text-orange-300" },
    ],
    topics: [
      "Origem do Sistema Solar",
      "Estrutura interna dos planetas",
      "Origem da Lua",
      "Evolução do Sol",
    ],
    tags: [
      { title: "5°ano", color: "text-emerald-500" },
      { title: "6°ano", color: "text-emerald-600" },
      { title: "7°ano", color: "text-emerald-700" },
      { title: "8°ano", color: "text-emerald-800" },
      { title: "9°ano", color: "text-emerald-900" },
    ],
  },
  {
    id: 13,
    title: "Vingança do Clima",
    type: "planetarium",
    images: [
      "/images/Planetarios/Vingança do Clima/Imagem Plana.jpg",
      "/images/Planetarios/Vingança do Clima/Vinganca do Clima.jpg",
    ],
    description: `Transportados para um futuro distante, os alunos conhecem seres extraterrestres que descobrem o planeta Terra e se deparam com as implicações, hoje previstas e que estão se concretizando, sobre o aquecimento global. São apresentados cenários futuros onde ocorreram o derretimento das geleiras e aumento do nível dos mares. São discutidos os impactos das intervenções humanas no equilíbrio do planeta.`,
    subjects: [
      { title: "Ciências", color: "text-blue-300" },
      { title: "Meio Ambiente", color: "text-green-300" },
      { title: "Geografia", color: "text-orange-300" },
    ],
    topics: ["Biosfera", "Meio Ambiente", "Aquecimento Global", "Desmatamento"],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "6°ano", color: "text-emerald-600" },
      { title: "7°ano", color: "text-emerald-700" },
      { title: "8°ano", color: "text-emerald-800" },
      { title: "9°ano", color: "text-emerald-900" },
      { title: "1°ano[E.M.]", color: "text-lime-100" },
      { title: "2°ano[E.M.]", color: "text-lime-200" },
      { title: "3°ano[E.M.]", color: "text-lime-300" },
    ],
  },
  {
    id: 14,
    title: "O Sopro da Vida",
    type: "planetarium",
    images: [
      "/images/Planetarios/Sopro da Vida/DNA - 1500x1500.jpg",
      "/images/Planetarios/Sopro da Vida/Sopro da Vida Plano.jpg",
    ],
    description: `A ideia dessa sessão é estudar a vida a partir de uma célula primordial. Para entender como a vida surgiu nos oceanos primitivos da Terra, voltamos no tempo, entramos em uma célula gigante para conhecer suas organelas. Dentro de um organismo, conhecemos alguns órgãos e sistemas até o cérebro humano.`,
    subjects: [
      { title: "Biologia", color: "text-green-200" },
      { title: "Ciências", color: "text-blue-300" },
    ],
    topics: [
      "Formação do ambiente propício a vida",
      "Surgimento e evolução da vida",
      "Moléculas orgânicas, DNA",
      "Célula e organelas celulares",
      "Tecidos, órgãos e sistemas",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "6°ano", color: "text-emerald-600" },
      { title: "7°ano", color: "text-emerald-700" },
      { title: "8°ano", color: "text-emerald-800" },
      { title: "9°ano", color: "text-emerald-900" },
      { title: "1°ano[E.M.]", color: "text-lime-100" },
      { title: "2°ano[E.M.]", color: "text-lime-200" },
      { title: "3°ano[E.M.]", color: "text-lime-300" },
    ],
  },
  {
    id: 15,
    title: "O Reino da Luz",
    type: "planetarium",
    images: [
      "https://images.pexels.com/photos/15326066/pexels-photo-15326066/free-photo-of-show-concerto-apresentacao-sombrio.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    ],
    description: `Com lindas imagens e olhando para as estrelas, os espectadores são convidados a contemplar e refletir filosoficamente sobre a origem do Universo e da vida como a conhecemos.`,
    subjects: [
      { title: "Biologia", color: "text-green-200" },
      { title: "Ciências", color: "text-blue-300" },
      { title: "Filosofia", color: "text-yellow-700, " },
    ],
    topics: [
      "Formação do Universo",
      "Formação da Terra",
      "Surgimento e evolução da vida",
    ],
    tags: [
      { title: "6°ano", color: "text-emerald-600" },
      { title: "7°ano", color: "text-emerald-700" },
      { title: "8°ano", color: "text-emerald-800" },
      { title: "9°ano", color: "text-emerald-900" },
      { title: "1°ano[E.M.]", color: "text-lime-100" },
    ],
  },
  {
    id: 14,
    title: "Uma Noite com 100 Bilhões de Estrelas",
    type: "planetarium",
    images: [
      "/images/Planetarios/100 Bilhoes de Estrelas/Galaxia 01.jpg",
      "/images/Planetarios/100 Bilhoes de Estrelas/Nebulosa de Orion.jpg",
    ],
    description: `Em uma viagem espacial simulada, atravessamos a estrutura da Via Láctea para conhecer diferentes objetos astronômicos que compõem nossa Galáxia. A simulação proporciona a experiência de observar a paisagem de uma região até então, inalcansável para a humanidade.`,
    subjects: [
      { title: "Astronomia", color: "text-blue-300" },
      { title: "Geografia", color: "text-orange-300" },
      { title: "Física", color: "text-green-500" },
      { title: "Ciências", color: "text-blue-300" },
    ],
    topics: [
      "Estrutura da Via-Láctea",
      "Estrelas",
      "Nebulosas",
      "Buracos Negros",
      "Aglomerados Estelares",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "6°ano", color: "text-emerald-600" },
      { title: "7°ano", color: "text-emerald-700" },
      { title: "8°ano", color: "text-emerald-800" },
      { title: "9°ano", color: "text-emerald-900" },
      { title: "1°ano[E.M.]", color: "text-lime-100" },
      { title: "2°ano[E.M.]", color: "text-lime-200" },
      { title: "3°ano[E.M.]", color: "text-lime-300" },
    ],
  },
  {
    id: 15,
    title: "Universo Líquido",
    type: "planetarium",
    images: [
      "/images/Planetarios/Universo Líquido/Universo Liquido Plano.jpg",
      "/images/Planetarios/Universo Líquido/Universo Liquido.jpg",
    ],
    description: `Dada a importância da água líquida para o surgimento e manutenção da vida na Terra, a sessão apresenta a água enquanto substância química e sua importância como solvente universal. A seguir viajamos pelo Universo para explicar o origem da água e de seus elementos componentes, Hidrogênio e Oxigênio e ainda discutimos sua disponibilidade em outros locais no universo, como a nossa Lua, outros planetas e exoplanetas.`,
    subjects: [
      { title: "Astronomia", color: "text-blue-300" },
      { title: "Física", color: "text-green-500" },
      { title: "Química", color: "text-blue-900" },
      { title: "Ciências", color: "text-blue-300" },
    ],
    topics: [
      "Características físicas das água",
      "Água na Terra",
      "Origem da água e do hidrogênio e oxigênio",
      "Água no Universo",
      "Água em exoplanetas",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "7°ano", color: "text-emerald-700" },
      { title: "8°ano", color: "text-emerald-800" },
      { title: "9°ano", color: "text-emerald-900" },
      { title: "1°ano[E.M.]", color: "text-lime-100" },
      { title: "2°ano[E.M.]", color: "text-lime-200" },
      { title: "3°ano[E.M.]", color: "text-lime-300" },
    ],
  },
  {
    id: 16,
    title: "Mundos Vivos",
    type: "workshop",
    images: [
      "https://images.pexels.com/photos/10161677/pexels-photo-10161677.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    ],
    description: `Na primeira parte da oficina, os estudantes são divididos em grupos onde cada um representa um planeta, e seguindo instruções de medida, criam uma maquete em escala do Sistema Solar. A seguir é realizada uma gincana, onde os alunos são obrigados a discutir entre si e trocar informações para responder perguntas sobre os objetos do Sistema Solar.`,
    subjects: [
      { title: "Astronomia", color: "text-blue-300" },
      { title: "Ciências", color: "text-blue-300" },
      { title: "Matemática", color: "text-yellow-200" },
      { title: "Geografia", color: "text-orange-300" },
    ],
    topics: [
      "Proporção e escala",
      "Distância entre planetas do Sistema Solar",
      "Características dos planetas",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "5°ano", color: "text-emerald-500" },
      { title: "6°ano", color: "text-emerald-600" },
      { title: "7°ano", color: "text-emerald-700" },
    ],
  },
  {
    id: 17,
    title: "Fobos: O Fogute",
    type: "workshop",
    images: [
      "https://images.pexels.com/photos/87089/rocket-lift-off-liftoff-astronautics-87089.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    ],
    description: `Inicialmente é feita uma breve introdução sobre a estrutura de um foguete, seu tipo de combustível e como será o roteiro da atividade. A seguir, na base de lançamento, com casamata para proteger a equipe e torre de lançamento, os alunos realizam os procedimentos para o lançamento de um minifoguete. Os estudantes trabalham em equipe e seus integrantes têm funções específicas como  para ignição, segurança e resgate.`,
    subjects: [
      { title: "Astronáutica", color: "text-blue-500" },
      { title: "Química", color: "text-blue-900" },
      { title: "Física", color: "text-green-500" },
      { title: "Ciências", color: "text-blue-300" },
    ],
    topics: [
      "Terceira Lei de Newton ( acão e reação )",
      "Programa espacial brasileiro",
      "Procedimentos de segurança",
      "Propelentes",
      "Dinâmica de trabalho em equipe",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "5°ano", color: "text-emerald-500" },
      { title: "6°ano", color: "text-emerald-600" },
      { title: "7°ano", color: "text-emerald-700" },
      { title: "8°ano", color: "text-emerald-800" },
      { title: "9°ano", color: "text-emerald-900" },
      { title: "1°ano[E.M.]", color: "text-lime-100" },
      { title: "2°ano[E.M.]", color: "text-lime-200" },
      { title: "3°ano[E.M.]", color: "text-lime-300" },
    ],
  },
  {
    id: 18,
    title: "O Céu na Régua e Compasso",
    type: "workshop",
    images: [
      "https://images.pexels.com/photos/15206853/pexels-photo-15206853/free-photo-of-crepusculo-cair-da-noite-fim-da-tarde-lago.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    ],
    description: `Nessa oficina a teoria se junta a prática. Cada estudante monta o seu próprio relógio solar horizontal e com matemática e geometria básicas, compreende o movimento aparente do Sol, aprende a posicionar seu relógio e compara com o relógio solar analemático no jardim do CEU.`,
    subjects: [
      { title: "Astronomia", color: "text-blue-300" },
      { title: "Ciências", color: "text-blue-300" },
      { title: "Matemática", color: "text-yellow-200" },
      { title: "Geografia", color: "text-orange-300" },
    ],
    topics: [
      "Geometria básica",
      "Movimentos da Terra",
      "Movimento aparente do Sol",
      "Coordenadas geográficas",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "5°ano", color: "text-emerald-500" },
      { title: "6°ano", color: "text-emerald-600" },
      { title: "7°ano", color: "text-emerald-700" },
    ],
  },
  {
    id: 19,
    title: "Identificação de Rochas",
    type: "workshop",
    images: [
      "https://images.pexels.com/photos/1029604/pexels-photo-1029604.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    ],
    description: `Dentro da caverna cenográfica, é feita uma rápida introdução aos tipos de rocha que existem na Terra e sobre o ciclo de rochas. Também é fornecido um texto com pistas e um diagrama para auxiliar na identificação das rochas que serão encontradas nas paredes da caverna. Os alunos trabalham em grupos coletando as rochas simulando uma escavação. Em seguida, os grupos podem analisar as rochas com o objetivo de compreender o ciclo das rochas e identificar quais são as sedimentares, magmáticas e metamórficas. As amostras são de rochas reais extraídas de nove regiões específicas do Brasil.`,
    subjects: [
      { title: "Geologia", color: "text-orange-600" },
      { title: "Geografia", color: "text-orange-300" },
    ],
    topics: [
      "Formação da Terra",
      "Tipos de rochas ( Magmáticas, Metamórficas e Sedimentares )",
      "Ciclo das Rochas",
      "Identificação de 9 exemplos de rochas ( mármore, diabásico, gnaisse, quartzito, vervito, granito, arenito, calcário e basalto )",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "6°ano", color: "text-emerald-600" },
      { title: "7°ano", color: "text-emerald-700" },
      { title: "8°ano", color: "text-emerald-800" },
      { title: "9°ano", color: "text-emerald-900" },
    ],
  },
  {
    id: 20,
    title: "Desvendando Gaia ( Oficina de Fósseis )",
    type: "workshop",
    images: [
      "https://images.pexels.com/photos/2726724/pexels-photo-2726724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    ],
    description: `Num paredão com o perfil geológico do Estado de São Paulo no interior da Caverna, os alunos coletam réplicas de fósseis de diferentes períodos geológicos afim de descrevê-los: são dentes, pegadas, esqueletos e outros vestígios e restos, os quais os alunos identificam e classificam em suas planilhas de paleontólogos. Ao final da atividade, durante a exposição dos fósseis coletados, é possível demonstrar a evolução da complexidade dos organismos vivos através de uma linha do tempo.`,
    subjects: [
      { title: "Geografia", color: "text-orange-300" },
      { title: "Paleontologia", color: "text-orange-800" },
      { title: "Ciências", color: "text-blue-300" },
    ],
    topics: [
      "Períodos geológicos",
      "Formação de fósseis",
      "Restos e vetígios",
      "Identificação de réplicas de fósseis de diferentes períodos geológicos",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "6°ano", color: "text-emerald-600" },
      { title: "7°ano", color: "text-emerald-700" },
      { title: "8°ano", color: "text-emerald-800" },
      { title: "9°ano", color: "text-emerald-900" },
    ],
  },
  {
    id: 21,
    type: "special",
    title: "Observação",
    images: [
      "/images/atendimentoPublico/publico-8.jpg ",
      "/images/atendimentoPublico/obs-sara.jpg ",
      "/assets/telescopio-2.jpeg",
      "/images/atendimentoPublico/publico-10.jpg ",
      "/images/atendimentoPublico/publico-11.jpg",
    ],
    description: `Iniciamos a atividade com uma pequena introdução realizada no auditório onde explicamos como deve ser feita a observação e quais os astros que iremos observar na noite em questão. A seguir os alunos são divididos em grupos e passam por todos os telescópios que estiverem sendo usados na noite, para ver um astro diferente em cada equipamento.`,
    subjects: [
      { title: "Inglês", color: "text-red-400" },
      { title: "Astronomia", color: "text-blue-300" },
      { title: "Ciências", color: "text-blue-300" },
    ],
    topics: [
      "Uso de telescópios",
      "Observação de astros ( planetas, aglomerados, nebulosas, constelações)",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "1°ano", color: "text-emerald-100" },
      { title: "2°ano", color: "text-emerald-200" },
      { title: "3°ano", color: "text-emerald-300" },
      { title: "4°ano", color: "text-emerald-400" },
      { title: "5°ano", color: "text-emerald-500" },
      { title: "6°ano", color: "text-emerald-600" },
      { title: "7°ano", color: "text-emerald-700" },
      { title: "8°ano", color: "text-emerald-800" },
      { title: "9°ano", color: "text-emerald-900" },
      { title: "1°ano[E.M.]", color: "text-lime-100" },
      { title: "2°ano[E.M.]", color: "text-lime-200" },
      { title: "3°ano[E.M.]", color: "text-lime-300" },
    ],
  },
  {
    id: 22,
    type: "special",
    title: "Geo Show",
    images: [
      "/images/structure/geoshow-nite.jpeg",
      "/images/structure/geo-show.jpeg",
      "/images/structure/geoshow2.jpeg",
    ],
    description: `Em um paredão externo com o formato do perfil geológico do estado de São Paulo, acontece um show noturno, onde a própria Terra (representada pela deusa grega Gaia) narra a sua estória, desde a expansão que criou o Universo, até o aparecimento de estrelas, galáxias, nosso Sol e a formação de nosso planeta. Neste show, cada camada geológica é acessa e um telão exibe as informações sobre seu período no tempo, suas características, sua fauna e flora e principais acontecimentos. O show termina com o aparecimento do homem e sua influência sobre o meio ambiente do planeta.`,
    subjects: [
      { title: "Inglês", color: "text-red-400" },
      { title: "Meio Ambiente", color: "text-green-300" },
      { title: "Biologia", color: "text-green-200" },
      { title: "Geografia", color: "text-orange-300" },
      { title: "Geologia", color: "text-orange-600" },
    ],
    topics: [
      "Formação do Universo e da Terra",
      "Surgimento e evolução da vida",
      "Características dos diferentes períodos geológicos",
      "Formação do relevo do estado de São Paulo",
      "Impacto das ações humanas no meio ambiente",
    ],
    tags: [
      { title: "Inglês", color: "text-red-400" },
      { title: "6°ano", color: "text-emerald-600" },
      { title: "7°ano", color: "text-emerald-700" },
      { title: "8°ano", color: "text-emerald-800" },
      { title: "9°ano", color: "text-emerald-900" },
      { title: "1°ano[E.M.]", color: "text-lime-100" },
      { title: "2°ano[E.M.]", color: "text-lime-200" },
      { title: "3°ano[E.M.]", color: "text-lime-300" },
    ],
  },
];

const services = [
  {
    title: "Atendimento ao Público",
    icon: web,
    link: "/publico",
  },
  {
    title: "Escolas & Colégios",
    icon: mobile,
    link: "/escolas",
  },
  {
    title: "Eventos Corporativos",
    icon: creator,
    link: "/corporativo",
  },
];

const technologies = [
  {
    name: "HTML 5",
    icon: html,
  },
  {
    name: "CSS 3",
    icon: css,
  },
  {
    name: "JavaScript",
    icon: javascript,
  },
  {
    name: "TypeScript",
    icon: typescript,
  },
  {
    name: "React JS",
    icon: reactjs,
  },
  {
    name: "Redux Toolkit",
    icon: redux,
  },
  {
    name: "Tailwind CSS",
    icon: tailwind,
  },
  {
    name: "Node JS",
    icon: nodejs,
  },
  {
    name: "MongoDB",
    icon: mongodb,
  },
  {
    name: "Three JS",
    icon: threejs,
  },
  {
    name: "git",
    icon: git,
  },
  {
    name: "figma",
    icon: figma,
  },
  {
    name: "docker",
    icon: docker,
  },
];

const publicActivities = [
  {
    title: "Observação",
    company_name: "por Telescópio",
    icon: observacao,
    iconBg: "#E6DEDD", //"#383E56",
    date: "A atividade está sujeita às condições meteorológicas. Em caso de céu nublado/chuvoso, ela será substituída e o público receberá um voucher para retornar e realizar a observação gratuitamente em outra noite de atendimento ao público e mediante aviso prévio.",
    points: [
      "Em noites com boas condições do tempo, a observação é a primeira atividade realizada.",
      "O público é levado para o Auditório, onde recebe instruções sobre as atividades da noite e as técnicas de observação.",
      "Após a introdução, as pessoas sobem até a laje de observação onde os professores realizam o reconhecimento de céu e explicam sobre os objetos que serão vistos.",
      "A quantidade de telescópios e de astros a serem observados ficam a critério dos professores.",
    ],
  },
  {
    title: "Sessão de Planetário",
    company_name: "",
    icon: planetarium,
    iconBg: "#383E56",
    date: "",
    points: [
      "Após um breve intervalo entre a observação e a segunda atividade, o público é levado ao planetário, onde assiste à uma sessão de contemplação dos objetos no céu.",
      "Durante todo o período de atividades e mesmo após o planetário, os professores estarão disponíveis a tirar dúvidas e ouvir os comentários das pessoas que desejarem fazê-lo.",
      "Ao término do planetário, o público já fica liberado para, se assim desejar, deixar o CEU e retornar à Terra.",
    ],
  },
];

const experiences = [
  {
    title: "React.js Developer",
    company_name: "Starbucks",
    icon: starbucks,
    iconBg: "#383E56",
    date: "March 2020 - April 2021",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "React Native Developer",
    company_name: "Tesla",
    icon: tesla,
    iconBg: "#E6DEDD",
    date: "Jan 2021 - Feb 2022",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Web Developer",
    company_name: "Shopify",
    icon: shopify,
    iconBg: "#383E56",
    date: "Jan 2022 - Jan 2023",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Full stack Developer",
    company_name: "Meta",
    icon: meta,
    iconBg: "#E6DEDD",
    date: "Jan 2023 - Present",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
];

const testimonials = [
  {
    testimonial:
      "I thought it was impossible to make a website as beautiful as our product, but Rick proved me wrong.",
    name: "Sara Lee",
    designation: "CFO",
    company: "Acme Co",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    testimonial:
      "I've never met a web developer who truly cares about their clients' success like Rick does.",
    name: "Chris Brown",
    designation: "COO",
    company: "DEF Corp",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    testimonial:
      "After Rick optimized our website, our traffic increased by 50%. We can't thank them enough!",
    name: "Lisa Wang",
    designation: "CTO",
    company: "456 Enterprises",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
  },
];

const projects = [
  {
    name: "Car Rent",
    description:
      "Web-based platform that allows users to search, book, and manage car rentals from various providers, providing a convenient and efficient solution for transportation needs.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },
      {
        name: "mongodb",
        color: "green-text-gradient",
      },
      {
        name: "tailwind",
        color: "pink-text-gradient",
      },
    ],
    image: carrent,
    source_code_link: "https://github.com/",
  },
  {
    name: "Job IT",
    description:
      "Web application that enables users to search for job openings, view estimated salary ranges for positions, and locate available jobs based on their current location.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },
      {
        name: "restapi",
        color: "green-text-gradient",
      },
      {
        name: "scss",
        color: "pink-text-gradient",
      },
    ],
    image: jobit,
    source_code_link: "https://github.com/",
  },
  {
    name: "Trip Guide",
    description:
      "A comprehensive travel booking platform that allows users to book flights, hotels, and rental cars, and offers curated recommendations for popular destinations.",
    tags: [
      {
        name: "nextjs",
        color: "blue-text-gradient",
      },
      {
        name: "supabase",
        color: "green-text-gradient",
      },
      {
        name: "css",
        color: "pink-text-gradient",
      },
    ],
    image: tripguide,
    source_code_link: "https://github.com/",
  },
];

export {
  services,
  technologies,
  experiences,
  testimonials,
  projects,
  activities,
  activitiesList,
  structure,
  publicActivities,
};
